

/*================================================================
 *   
 *   
 *   文件名称：charger_bms_gb.h
 *   创 建 者：肖飞
 *   创建日期：2021年04月10日 星期六 17时01分34秒
 *   修改日期：2021年04月10日 星期六 21时52分11秒
 *   描    述：
 *
 *================================================================*/
#ifndef _CHARGER_BMS_GB_H
#define _CHARGER_BMS_GB_H
#ifdef __cplusplus
extern "C"
{
#endif

#include "app_platform.h"
#include "cmsis_os.h"

#include "charger.h"

#ifdef __cplusplus
}
#endif

typedef enum {
	CHARGER_BMS_STATE_IDLE = 0,
	CHARGER_BMS_STATE_CHM,
	CHARGER_BMS_STATE_CRM,
	CHARGER_BMS_STATE_CTS_CML,
	CHARGER_BMS_STATE_CRO,
	CHARGER_BMS_STATE_CCS,
	CHARGER_BMS_STATE_CST,
	CHARGER_BMS_STATE_CSD_CEM,
} charger_bms_state_t;

typedef enum {
	CHARGER_BMS_INFO_STATUS_CHANGE = 0,
	CHARGER_BMS_INFO_STATUS_CHM_OUTPUT_VOLTAGE_UNMATCH,
	CHARGER_BMS_INFO_STATUS_CHM_OP_STATE_DISCHARGE_TIMEOUT,
	CHARGER_BMS_INFO_STATUS_CHM_OP_STATE_RELAY_ENDPOINT_OVERVOLTAGE_CHECK_TIMEOUT,
	CHARGER_BMS_INFO_STATUS_CHM_OP_STATE_INSULATION_CHECK_PRECHARGE_TIMEOUT,
	CHARGER_BMS_INFO_STATUS_CHM_OP_STATE_INSULATION_CHECK_TIMEOUT,
	CHARGER_BMS_INFO_STATUS_CHM_OP_STATE_INSULATION_CHECK_STOP_PRECHARGE_TIMEOUT,
	CHARGER_BMS_INFO_STATUS_CHM_OP_STATE_INSULATION_CHECK_DISCHARGE_TIMEOUT,
	CHARGER_BMS_INFO_STATUS_CRO_OP_STATE_GET_BATTERY_STATUS_TIMEOUT,
	CHARGER_BMS_INFO_STATUS_BRM_TIMEOUT,
	CHARGER_BMS_INFO_STATUS_BCP_TIMEOUT,
	CHARGER_BMS_INFO_STATUS_BRO_TIMEOUT,
	CHARGER_BMS_INFO_STATUS_CRO_OUTPUT_VOLTAGE_UNMATCH,
	CHARGER_BMS_INFO_STATUS_CRO_OP_STATE_PRECHARGE_TIMEOUT,
	CHARGER_BMS_INFO_STATUS_BCL_TIMEOUT,
	CHARGER_BMS_INFO_STATUS_BCS_TIMEOUT,
	CHARGER_BMS_INFO_STATUS_CSD_CEM_OP_STATE_DISCHARGE_TIMEOUT,
	CHARGER_BMS_INFO_STATUS_CST,
	CHARGER_BMS_INFO_STATUS_BHM_RECEIVED,
	CHARGER_BMS_INFO_STATUS_BRM_RECEIVED,
	CHARGER_BMS_INFO_STATUS_BCP_RECEIVED,
	CHARGER_BMS_INFO_STATUS_BRO_RECEIVED,
	CHARGER_BMS_INFO_STATUS_BCL_RECEIVED,
	CHARGER_BMS_INFO_STATUS_BCS_RECEIVED,
	CHARGER_BMS_INFO_STATUS_BSM_RECEIVED,
	CHARGER_BMS_INFO_STATUS_BST_RECEIVED,
	CHARGER_BMS_INFO_STATUS_BSD_RECEIVED,
	CHARGER_BMS_INFO_STATUS_BEM_RECEIVED,
} charger_bms_info_status_t;

extern charger_bms_handler_t charger_bms_handler_gb;

#endif //_CHARGER_BMS_GB_H
